server:
  port: 7070

## Dubbo 服务消费者配置
#应用名
spring:
  dubbo:
    application:
      name: consumer
    #zookeeper的注册地址
    registry:
      address: zookeeper://127.0.0.1:2181
    #扫描消费者控制层映射到dubbo中,由它管理
    scan: com.java.consumer.controller